PREFIX : <http://jms.ws-examples/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?person ?sName
WHERE {
       ?person a ?type
        OPTIONAL{?person rdfs:label ?sName.}
        FILTER(?type = :Man || ?type = :Woman)
}
ORDER BY ASC(?sName)
