DELETE FROM AULA_DIASSEMANA
DELETE FROM INSCRICAO
DELETE FROM AULAATIVA
DELETE FROM AULA
INSERT INTO INSCRICAO(INSCRICAO_ID, TIPO, DESCRICAO) VALUES (1, 1, 'AVULSA')
INSERT INTO INSCRICAO(INSCRICAO_ID, TIPO, DESCRICAO) VALUES (2, 2, 'REGULAR')